### PR TITLE
updated .net core build task to version 2

### PR DESCRIPTION
**Pull request by joe45sp**
Updated the .net core build task versions in the vsts build definition from version 1 to 2

### CODE REVIEW

**Comment by joe45sp** [comment]
@DarqueWarrior it seems the private build agent is no longer working. Can you update the build to use the hosted VSTS agent instead?

**Comment by DarqueWarrior** [comment]
I will be looking at all the PRs tomorrow and see what is going on. Thanks.

**Comment by DarqueWarrior** [comment]
The build works as expected from master. I will see why it is not working from the PRs.

**Comment by joe45sp** [comment]
Awesome, thank you @DarqueWarrior!!! I'd love to start helping out more with this project, so any way at all that I can help, please let me know! One feature I would like to start working on is automatically adding pull request policies after the git repository is created.

**Comment by joe45sp** [comment]
Looking at the API documentation, looks like that feature isn't available do to yet. But if there's anything else you can think of for me to help out with, I'd be more than happy to help!

**Comment by DarqueWarrior** [comment]
The issue is with how I clone the repo for the build. VSTS clones into a s folder. That does not work for npm modules. The folder name must match the module name. My original solution only works when pulled from master. I am fixing it now to work with PRs as well. Thanks for your patience and support.

**Comment by DarqueWarrior** [comment]
When I run integration tests my builds are failing saying no test results are found.

**Comment by DarqueWarrior** [comment]
Looks like it has to do with the box being checked to publish tests results with the same task.  When I revert to v1 of the task everything works as expected. I will continue to test and try to correct the build defs. Just changing the version to 2.* breaks the builds.  It sets defaults that don't work with the flow.

**Comment by DarqueWarrior** [comment]
The hosted build agents are broken at the moment so all my integration tests are failing once they are patched I will return to this.

**Comment by joe45sp** [comment]
@DarqueWarrior any luck with getting the build to succeed?

**Comment by DarqueWarrior** [comment]
I will be working on Yo Team this weekend. I have to update the pipeline that tests everything. Sorry for the delay.

**Pull request merged**
