### PR TITLE
PowerShell Module Project and Publish To PowerShell Gallery

### PR DESCRIPTION
**Pull request by smurawski**
This is an initial implementation of a build and release pipeline for PowerShell projects.  It can scaffold out a PowerShell module, set up the project and build pipeline, then add a release pipeline for publishing to the PowerShell Gallery.

This could be merged and shipped as is, or below I have some additional capabilities to add (which could be follow on pull requests).

### CODE REVIEW

**Comment by DarqueWarrior** [comment]
Run mocha on your branch. There are a lot of test failing now 10 of the 199 tests.  If you run npm test you can also see a drop in code coverage. On the Master branch the code coverage is 100%.

**Comment by DarqueWarrior** [comment]
When would the answer to **Where would you like to deploy** ever not be PowerShell Gallery?  I don't see how we could add additional information for private.  If that is the only option don't prompt for the value. Just default to PowerShell Gallery until we support multiple targets.

You should hide PowerShell if the **Hosted Linux Preview** agent queue is selected. The build can't be queued against that agent queue.

**Comment by smurawski** [comment]
Fixed the broken tests and hid powershell as an option if Hosted Linux agent queue is selected.

I need to add some tests to get the code coverage back to where it was.

I don't think I'm behind master (unless you've got local commits that aren't pushed to github).  I pulled from your repo and tried a rebase against your master - which said I was up to date and the GitHub UI agrees.

I'll look at just setting the where to deploy if powershell is the project type.

**Comment by DarqueWarrior** [comment]
Curious why did you add PowerShell as the third option instead of adding it to the end?
Why are we asking this "Where would you like to deploy?" There is only one answer. 
Have you given any thought to just providing a publish script when you gen the project instead of using Inline PowerShell to publish? It is such a large piece of PowerShell it might be nice to hide the complexity.  Just a thought.

**Comment by DarqueWarrior** [comment]
There is code in place to load build and release defs for TFS but the files are not in the project. You need to test this against TFS 2017.

**Comment by smurawski** [comment]
| Curious why did you add PowerShell as the third option instead of adding it to the end?

Cargo-culted the aspfull technique due to lack of familiarity with javascript.  Changed it to a push.

| Why are we asking this "Where would you like to deploy?" There is only one answer.

Answered above - I just needed to figure out where I could set to quash the prompting.  

| Have you given any thought to just providing a publish script when you gen the project instead of using Inline PowerShell to publish? It is such a large piece of PowerShell it might be nice to hide the complexity. 

Yeah, I'd like to hide that blob of powershell, but haven't developed strong feelings about where that should end up - a release script in the project / a vsts task and service connection / something else?

I'm going to spin up TFS 2017 soon to test that end.

**Comment by DarqueWarrior** [comment]
Until we have an extension I think a deploy folder in the project with the script is fine.

**Comment by DarqueWarrior** [comment]
Looking really good.  I think you should prompt for Author so we can replace this 
   # Author of this module
   Author            = 'Unknown'

**Comment by smurawski** [comment]
@DarqueWarrior I just re-read your last comment, I'll update the behavior around the author, description, and readme. (and License URI is required for powershell gallery now I believe).

**Comment by smurawski** [comment]
The `team:powershell` generator now prompts for application name, author, and description.

The build for `powershell` projects will prompt for a pre-release gallery uri (like package management or myget or artifactory) and a nuget api key for that repository.

The release for `powershell` projects will prompt for the pre-release gallery (to pull the build artifact) and a nuget api key for the PowerShell gallery to publish the finished artifact.  A manual approval is required to push the artifact to the PowerShell Gallery.

**Comment by smurawski** [comment]
Generator added:

- `team:powershell`
  - prompts for 
    - application name (name of the Powershell Module)
    - author and description (for the module metadata
  - generates a small module with some basic Pester tests

Generators extended
- `team:build`
  - `powershell` builds for VSTS and TFS
  - prompts for 
    - prerelease gallery (nuget feed) API key and URI.  At the end of the build, the module is uploaded to a pre-release feed (could be MyGet or Package Management, or some other source).  The pre-release feed is an external requirement.
  - the build runs PSScriptAnalyzer for Lint and Syntax checks and Pester for unit tests

- `team:release`
  - `gallery` releases for `powershell` projects
  - prompts for 
    - Powershell Gallery API key
  - deploys the module from the pre-release gallery to the public gallery

**Comment by DarqueWarrior** [comment]
Make sure and lint the code. A lot of missing semicolons :) This is not PowerShell. :)

**Comment by smurawski** [comment]
@DarqueWarrior Do you have a good eslint rc?  It keeps blowing up on the `const` settings for me.

Also, moved the pre-release deploy to release (fits better with the other patterns).  We can also add a conditional around that if you just want to deploy to the PowerShell Gallery (not done yet).

**Comment by DarqueWarrior** [comment]
http://www.donovanbrown.com/post/Enabling-jshint-es6-support-in-VS-Code

**Comment by smurawski** [comment]
Closing this pending the creation of a VSTS extension to make for a cleaner build process.

**Pull request closed without merging**
